---
title: "Checkpoint1"
author: "Peter"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
data("Caterpillars")
data("RailTrail")
view(RailTrail)
```


```{r}
mymodel <-  lm(Mass~Fgp, data = Caterpillars)

as.factor(Caterpillars$Fgp)

summary(mymodel)

ggplot(Caterpillars, aes(Fgp, Mass)) +
         geom_point() +
         geom_smooth(method = "lm")

cor.test(Mass~Fgp, data = Caterpillars)
```


```{r}
3.6382-2.7051

3.6382-2.7051*2


-1.772 - .9331
```








```{r}
plot(mymodel, 1:2) 
```






Q2

```{r}
cor.test(volume~hightemp, data = RailTrail) #0.5825719
cor.test(volume~lowtemp, data = RailTrail) #0.1760858 
cor.test(volume~precip, data = RailTrail) #-0.232384 
```

```{r}
myhigh <- lm(volume~hightemp, data = RailTrail)
mylow <- lm(volume~lowtemp, data = RailTrail)
myprecip <- lm(volume~precip, data = RailTrail)


#summary(myhigh)
summary(mylow)
#summary(myprecip)

plot(mylow, 1:2)

ggplot(RailTrail, aes(lowtemp, volume)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
newlow <- data.frame(lowtemp = c(40))
predict.lm(mylow, newlow, interval="confidence", level=0.95)
```

```{r}
sqrt(0.1602)
```








