---
title: "Project1"
author: "Peter"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
file_path <- "/Users/PeterDunson/Desktop/diabetes.csv"

# Import the CSV file
diabetes <- read.csv(file_path, stringsAsFactors = FALSE)
```

```{r}
## stepwise regression (automated)
#1 fit the null model
none = lm(BloodPressure ~ 1, data=diabetes1)

#2 fit the full model
full = lm(BloodPressure ~ Pregnancies + Glucose + SkinThickness + Insulin + BMI + Age,
          data=diabetes1)

#3 calculate the MSE for the full model
MSE = (summary(full)$sigma)^2

#4 use the step() command for forward selection
step(none, scope=list(upper=full), scale = MSE)

```

```{r}
plot(diabetes)
```


```{r}
all1 = regsubsets(BloodPressure ~ Pregnancies + Glucose + SkinThickness + Insulin + BMI + Age, data=train)

# produce best model of each size
summaryHH(all1)

DBT <- lm(BloodPressure~ Pregnancies + Glucose + SkinThickness + Insulin + BMI + Age, data = train)
summary(DBT)

plot(DBT, 1:2)
```


```{r}
# fit all models possible using the predictors you want to consider
all1 = regsubsets(BloodPressure ~ Pregnancies + Glucose + SkinThickness + Insulin + BMI + Age, data=diabetes1)

# produce best model of each size
summaryHH(all1)

DBT <- lm(BloodPressure~ Pregnancies + Glucose + SkinThickness + Insulin + BMI + Age, data = diabetes1)
summary(DBT)

plot(DBT, 1:2)
```



```{r}
diabetes1$residuals <- residuals(DBT)
diabetes1$fitted <- fitted(DBT)

ggplot(diabetes1, aes(x = fitted, y = residuals, color = Outcome)) +
  geom_point() +
  labs(x = "Fitted values", y = "Residuals") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  theme_minimal()
```

```{r}
set.seed(1.51)
test_id1 = sample(1:733,200, replace=FALSE) 
test = diabetes1[test_id1,]
train = diabetes1[-test_id1,]
```


```{r}
diabetes$BloodPressure[diabetes$BloodPressure == 0] <- NA

diabetes1 <- diabetes %>%
  filter(!is.na(BloodPressure))

?summaryHH
```

```{r}
#Model: G I B A
#Glucose
#Insulin
#BMI
#Age

bestmodel <- lm(BloodPressure~Glucose + Insulin + BMI + Age, data = train)
summary(bestmodel)
```

```{r}
train$residuals <- residuals(bestmodel)
train$fitted <- fitted(bestmodel)


ggplot(train, aes(x = fitted, y = residuals, color = Outcome)) +
  geom_point() +
  labs(x = "Fitted values", y = "Residuals") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  theme_minimal()
```


```{r}
prediction1 <- predict(bestmodel, test)
prediction1

CVresids = test$BloodPressure - prediction1
mean(CVresids) #0.3750781
var(CVresids) #115.5126

(MSE = (summary(bestmodel)$sigma)^2) #127.1339

#want similar values^^^^

# compute correlation between predicted and actual 
# responses for testing data
r = cor(test$BloodPressure, prediction1)
r

# calculate shrinkage
(shrinkage = 0.197 - r^2) #0.0001255562
```



```{r}
plot(bestmodel, 1:4)
```


```{r}
bestmodel1 <- lm(BloodPressure~Glucose + Insulin + BMI + Age, data = diabetes1)
summary(bestmodel1)
```


```{r}
## calculating leverage (hat values)
h = hatvalues(bestmodel)
sort(h)

(mod.lev = 2*(4+1)/533) #0.01876173
(high.lev = 3*(4+1)/533) #0.02814259


## calculating Cook's Distance
CD = cooks.distance(bestmodel)
sort(CD)   # compare to 0.5 (mild) or 1

## examine leverage and Cook's Distance using residual plots
plot(bestmodel, 1:4)
```

```{r}
plot(rstudent(bestmodel)~bestmodel$fitted)
abline(h=0, col = "red")
abline(h=c(-3,-2,2,3), lty=2)
```

```{r}
#bestmodel1 <- lm(BloodPressure~Glucose + Insulin + BMI + Age, data = diabetes1)
#newx <- data.frame(Glucose = )

#predict.lm(bestmodel, newx, interval="confidence", level = .95)
#predict.lm(bestmodel, newx, interval="prediction", level = .95)
```

```{r}
bestmodel2 <- lm(BloodPressure~Glucose + Insulin + BMI + Age, data = diabetes1)
confint(bestmodel2, level = .95)
```

```{r}
# Your model
bestmodel2 <- lm(BloodPressure~Glucose + Insulin + BMI + Age, data = diabetes1)

# Let's assume you have some new data in a dataframe called 'newdata'
newdata <- data.frame(Glucose=121.0423, Insulin=83.60982, BMI=32.29277, Age=33.36153)

# Calculate prediction interval
pred_interval <- predict(bestmodel2, newdata=newdata, interval="prediction", level=0.95)

pred_interval

```













